name: goushuangshikuai
on:
  workflow_dispatch:
  schedule:
    - cron: '34 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: goushuangshikuai
        env:
          p21: ${{ secrets.p21 }}
        run: |
          echo $p21 | jq -r .on4314 | /bin/bash
          echo $zx39370 | jq -r .fqfnk092 | /bin/bash
          echo $wipzy988 | jq -r .ribde9 | /bin/bash

